### ISSUE TITLE
Offline issues

### ISSUE THREAD

**Issue by 157946a** [Tanguygab/PlaceholderAPI-PlayerList-Expansion#2]
I use offline and authorized, but can not display offline, only online, such as%playerlist_offline,perm,yes,list,jc% he does not display offline players with jc permissions, directly returns an empty string, but I have the jc permission for offline players, and I give it when the player is online

**Comment by Tanguygab** [comment]
![image](https://user-images.githubusercontent.com/45695833/143478700-c57ef4f6-6e30-4d65-981b-dec14c742671.png)
